# Create GitHub Release on `vx.y.z` tag push
# TODO: Release on 

name: Create release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get tag subject
        run: echo ::set-env name=TAG_SUBJECT::$(git tag -l --format='%(subject)' "$GITHUB_REF")

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ env.TAG_SUBJECT  }}
          draft: false
          prerelease: false
